In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [6]:
# Створення вектора `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1.
vector = np.random.rand(10)
print(vector.shape, vector)

# Створення матриці `matrix` типу `numpy.array` розмірності 3x3
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix.shape, matrix)

(10,) [0.77030383 0.57772557 0.77625574 0.35081964 0.48760584 0.98940612
 0.15086307 0.19904045 0.45416132 0.57739064]
(3, 3) [[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [20]:
print(vector)

# Додавання до кожного значення вектора `vector` число 10 і округлення кожного значення до 2 знаків після коми
vector_plus_10 = np.round(vector + 10, 2)
print(vector_plus_10)

# Помноження кожного елементу матриці на 2 без використання циклів
matrix_multiplied_by_2 = matrix * 2
print(matrix_multiplied_by_2)

# TODO: із завдання не чітко зрозуміло чи то треба з початковою змінною `vector` працювати чи з `vector_plus_10`
# Створення нового вектора, який містить квадрат кожного `vector` без циклів
vector_squared = np.square(vector)
print(vector_squared)

[0.77030383 0.57772557 0.77625574 0.35081964 0.48760584 0.98940612
 0.15086307 0.19904045 0.45416132 0.57739064]
[10.77 10.58 10.78 10.35 10.49 10.99 10.15 10.2  10.45 10.58]
[[22 28 34]
 [40 46 52]
 [58 64 70]]
[0.593368   0.33376683 0.60257298 0.12307442 0.23775946 0.97892446
 0.02275966 0.0396171  0.2062625  0.33337996]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [24]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

[[0.18 0.53]
 [0.75 0.47]
 [0.35 0.21]] [[0.17 0.58 0.75]
 [0.38 0.11 0.15]] [[0]
 [1]] [[0 1]
 [1 0]]


In [30]:
# 1 завдання
result_matrix = np.dot(B, A)
print('Завдання 1')
print(result_matrix, result_matrix.shape)

# 2 завдання
result_vector = np.dot(result_matrix, C)
print('Завдання 2')
print(result_vector, result_vector.shape)

# 3 завдання
result_matrix_2 = np.dot(result_matrix, D)
print('Завдання 3')
print(result_matrix_2, result_matrix_2.shape)

Завдання 1
[[0.7281 0.5202]
 [0.2034 0.2846]] (2, 2)
Завдання 2
[[0.5202]
 [0.2846]] (2, 1)
Завдання 3
[[0.5202 0.7281]
 [0.2846 0.2034]] (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [41]:
# 1 завдання
transposed_result_matrix = result_matrix.T
print('Завдання 1')
print(transposed_result_matrix, transposed_result_matrix.shape)

# 2 завдання
transposed_vector = vector.T
print('Завдання 2')
print(transposed_vector, transposed_vector.shape)
print('Зміна відсутня при транспонуванні вектора')

# 3 завдання
column_vector = np.expand_dims(vector, axis=1)
print('Завдання 3')
print(column_vector, column_vector.shape)
print('Бачимо, що це тепер стало розмірністю 10x1')

# 4 завдання
transposed_column_vector = column_vector.T
print('Завдання 4')
print(transposed_column_vector, transposed_column_vector.shape)
print('Бачимо, що це тепер стало розмірністю 1x10')

Завдання 1
[[0.7281 0.2034]
 [0.5202 0.2846]] (2, 2)
Завдання 2
[0.77030383 0.57772557 0.77625574 0.35081964 0.48760584 0.98940612
 0.15086307 0.19904045 0.45416132 0.57739064] (10,)
Зміна відсутня при транспонуванні вектора
Завдання 3
[[0.77030383]
 [0.57772557]
 [0.77625574]
 [0.35081964]
 [0.48760584]
 [0.98940612]
 [0.15086307]
 [0.19904045]
 [0.45416132]
 [0.57739064]] (10, 1)
Бачимо, що це тепер стало розмірністю 10x1
Завдання 4
[[0.77030383 0.57772557 0.77625574 0.35081964 0.48760584 0.98940612
  0.15086307 0.19904045 0.45416132 0.57739064]] (1, 10)
